1. Create a 3x3 array that contains a diagonal of nines.


In [8]:
import numpy as np

arr = np.diag([9, 9, 9])

print(arr)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


2. Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.


In [7]:

# Create a 4x4 ndarray with consecutive even numbers from 2 to 32
arr = np.arange(2, 33, 2).reshape(4, 4)
# Calculate the mean and standard deviation of the array
mean = np.mean(arr)
std = np.std(arr)

# Create a boolean indexing for values within 1/2 standard deviations of the mean
temp = (arr > (mean - 0.5*std)) & (arr < (mean + 0.5*std))

result = arr[temp]

print(result)

[14 16 18 20]


3. Create a 9x9 array that contains only zeros of type int.


In [6]:
arr = np.zeros((9, 9), dtype=int)

print(arr)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc...


In [5]:
n = int(input("Enter a number: "))

# create an array of zeros with shape (n, n)
arr = np.zeros((n, n),dtype=int)

# use broadcasting to set the columns to the wanted values
arr += np.arange(1, n+1)      #for example n= 2 >>>>>  arr= arr + [1,2]    [[0,0]>>>>>>>  [[1,2]
                             #                                              [0,0]]>>>>>>   [1,2]]

print(arr)


[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]]
